version: "3"

dotenv:
  - ".env"

vars:
  INFISICAL_CMD:
    sh: |
      if command -v infisical >/dev/null 2>&1; then
        echo "infisical run --env=dev -- "
      else
        echo ""
      fi

  COMPOSE_CMD:
    sh: |
      if command -v docker compose >/dev/null 2>&1; then echo "docker compose"; elif command -v docker-compose >/dev/null 2>&1; then echo "docker-compose"; else echo "docker compose"; fi

includes:
  frontend:
    taskfile: ./Taskfile/Taskfile.frontend.yml
    dir: ./frontend

  backend:
    taskfile: ./Taskfile/Taskfile.backend.yml
    dir: ./backend

tasks:
  default:
    desc: åˆ©ç”¨å¯èƒ½ãªã‚¿ã‚¹ã‚¯ä¸€è¦§ã‚’è¡¨ç¤º
    cmd: task --list

  # ----------------------------------------------------------------
  # å…¨ä½“æ“ä½œã‚³ãƒžãƒ³ãƒ‰
  # ----------------------------------------------------------------
  dev:
    desc: ðŸš€ ãƒ•ãƒ­ãƒ³ãƒˆã¨ãƒãƒƒã‚¯ã‚’åŒæ™‚ã«èµ·å‹• (InfisicalçµŒç”±)
    cmd: "{{.INFISICAL_CMD}} task dev:start"

  dev:start:
    internal: true
    deps:
      - task: backend:dev
      - task: frontend:dev

  install:
    desc: ðŸ“¦ å…¨ä½“ã®ä¾å­˜é–¢ä¿‚ã‚’ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«
    deps:
      - task: backend:install
      - task: frontend:install

  # ----------------------------------------------------------------
  # ã‚¤ãƒ³ãƒ•ãƒ©é–¢é€£
  # ----------------------------------------------------------------
  up:
    desc: DBã‚³ãƒ³ãƒ†ãƒŠãªã©ã‚’èµ·å‹•
    cmd: "{{.INFISICAL_CMD}} {{.COMPOSE_CMD}} up -d"

  down:
    desc: ã‚³ãƒ³ãƒ†ãƒŠã‚’åœæ­¢
    cmd: "{{.INFISICAL_CMD}} {{.COMPOSE_CMD}} down"

  # ----------------------------------------------------------------
  # ä¾¿åˆ©æ©Ÿèƒ½
  # ----------------------------------------------------------------
  sync:
    desc: Infisical ã®å€¤ã‚’ãƒ­ãƒ¼ã‚«ãƒ«ã® .env ã«æ›¸ãå‡ºã— (ã‚¨ãƒ‡ã‚£ã‚¿ç”¨)
    cmds:
      - infisical export --env=dev --format=dotenv > .env
      - cd frontend && infisical export --env=dev --format=dotenv > .env
      - cd backend && infisical export --env=dev --format=dotenv > .env
